apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 5
  selector:
    app: nginx
    tier: dev
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: dev
        environment: production
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
